<?xml version="1.0" ?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="package_name" value="ackermann_slam_sim"/>
  <xacro:property name="PI" value="3.14159265"/>
  
  <xacro:property name="L_x" value="0.4"/> <!-- Robot X axis (front-back) -->
  <xacro:property name="L_y" value="0.5"/>  <!-- Robot Y axis (left-right) -->
  <xacro:property name="base_elevation" value="0.14"/>
  <xacro:property name="wheelDiameter" value="0.35"/>
  <xacro:property name="wheelThickness" value="0.15"/>

  <xacro:arg name="base_color"    default="1.0 0.0 0.0 1.0"/>
  <xacro:arg name="lidar_frequency" default="10"/>
  <xacro:arg name="horizontal_samples"    default="360"/>
  <xacro:arg name="horizontal_resolution"    default="1"/>
  <xacro:arg name="horizontal_min_angle"    default="-3.14159"/>
  <xacro:arg name="horizontal_max_angle"    default="3.14159"/>
  <xacro:arg name="vertical_samples"    default="32"/>
  <xacro:arg name="vertical_resolution"    default="1"/>
  <xacro:arg name="vertical_min_angle"    default="-0.78539"/>
  <xacro:arg name="vertical_max_angle"    default="0.78539"/>
  <xacro:arg name="min_distance"    default="0.2"/>
  <xacro:arg name="max_distance"    default="100.0"/>
  <xacro:arg name="resolution"    default="0.017453"/>

  <xacro:arg name="imu_frequency"    default="50"/>
  
  
  
  <!-- Custom color (for Ign and RViz) -->
  <material name="gray">
    <color rgba="0.4 0.4 0.4 1.0"/>
  </material>
  
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_elevation}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${2*L_x+0.3} ${2*L_y-0.2} 0.1"/>
      </geometry>
      <material name="base_color"> <!-- Color in IGN and Rviz2 (inside visual tag) -->
        <color rgba="$(arg base_color)"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <geometry>
        <box size="${2*L_x+0.3} ${2*L_y-0.2} 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <mass value="1.14395"/>
      <inertia ixx="0.126164" ixy="0.0" ixz="0.0"  iyy="0.416519" iyz="0.0"  izz="0.481014" />
    </inertial>
  </link>


  <!-- WHEEL MACRO --> 
  <xacro:macro name="wheel" params="prefix parent_link joint_origin_xyz joint_origin_rpy visual_origin_xyz visual_origin_rpy wheelSide">

    <joint name="${prefix}_joint" type="revolute">
      <origin xyz="${joint_origin_xyz}" rpy="${joint_origin_rpy}"/>
      <parent link="${parent_link}"/>
      <child link="${prefix}_link"/>
      <axis xyz="0 0 1"/>
      <limit lower="-1.79769e+308" upper="1.79769e+308" effort="40" velocity="2.0"/>
    </joint>

    <link name="${prefix}_link">
      <visual>
        <origin xyz="${visual_origin_xyz}" rpy="${visual_origin_rpy}"/>
        <geometry>
          <mesh filename="package://${package_name}/meshes/husky_wheel.stl" scale="1.0 0.9 1.0"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheelThickness}" radius="${wheelDiameter/2}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.1" />
        <inertia ixx="6.1e-5" ixy="0" ixz="0" iyy="6.1e-5" iyz="0" izz="6.1e-5"/>
      </inertial>
    </link>  
  </xacro:macro>
    
  
  <!-- Wheels definition (joints and links USING MACROS) -->
  <!-- left_front_wheel (M1) -->
  <xacro:wheel prefix="leftfront" parent_link="front_left_wheel_steering_link" joint_origin_xyz="0 0 0" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="left"/>
  
  <!-- right_front_wheel (M2) -->
  <xacro:wheel prefix="rightfront" parent_link="front_right_wheel_steering_link" joint_origin_xyz="0 0 0" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="right"/>
  
  <!-- right_back_wheel (M3) -->
  <xacro:wheel prefix="rightback" parent_link="base_link" joint_origin_xyz="${-L_x} ${-L_y} 0.01" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="left"/>
  
  <!-- left_back_wheel (M4) -->
  <xacro:wheel prefix="leftback" parent_link="base_link" joint_origin_xyz="${-L_x} ${L_y} 0.01" 
  joint_origin_rpy="${-PI/2} 0 0" visual_origin_xyz="0 0 0" visual_origin_rpy="${-PI/2} 0 0" wheelSide="right"/>




<!-- Joint de dirección: base_link -> front_left_wheel_steering_link -->
<joint name="front_left_wheel_steering_joint" type="revolute">
  <parent link="base_link"/>
  <child  link="front_left_wheel_steering_link"/>
  <origin xyz="${L_x} ${L_y} 0.01" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>                           <!-- gira en yaw -->
  <limit lower="-0.6" upper="0.6" effort="40" velocity="2.0"/>
  <dynamics damping="0.2" friction="0.0"/>      <!-- opcional, más estable -->
</joint>
<link name="front_left_wheel_steering_link">
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="0.5"/>
    <!-- Inercia física sugerida para cilindro sólido: m=0.5 kg, L=0.1 m, r=0.03 m -->
    <!-- Izz = 0.5*m*r^2 = 0.000225; Ixx=Iyy = (1/12)*m*(3r^2 + L^2) ≈ 0.000529 -->
    <inertia ixx="0.000529" ixy="0" ixz="0" iyy="0.000529" iyz="0" izz="0.000225"/>
  </inertial>
  <visual name="steering_link_visual">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder length="0.1" radius="0.03"/>
    </geometry>
    <material name="white">
      <color rgba="1 1 1 1"/>
    </material>
  </visual>
  <collision name="steering_link_collision">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder length="0.1" radius="0.03"/>
    </geometry>
  </collision>
</link>

<!-- Joint de dirección: base_link -> front_right_wheel_steering_link -->
<joint name="front_right_wheel_steering_joint" type="revolute">
  <parent link="base_link"/>
  <child  link="front_right_wheel_steering_link"/>
  <origin xyz="${L_x} ${-L_y} 0.01" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>   <!-- yaw -->
  <limit lower="-0.6" upper="0.6" effort="40" velocity="2.0"/>
  <dynamics damping="0.2" friction="0.0"/>
</joint>
<link name="front_right_wheel_steering_link">
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="0.5"/>
    <inertia ixx="0.000529" ixy="0" ixz="0" iyy="0.000529" iyz="0" izz="0.000225"/>
  </inertial>
  <visual name="steering_link_visual">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder length="0.1" radius="0.03"/>
    </geometry>
    <material name="white">
      <color rgba="1 1 1 1"/>
    </material>
  </visual>
  <collision name="steering_link_collision">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder length="0.1" radius="0.03"/>
    </geometry>
  </collision>
</link>

  <!-- ************************* SENSOR DEFINITIONS ************************* -->
  <!-- LIDAR -->
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="-0.04 0 0.07" rpy="0 0 0"/>
  </joint>
  <link name="lidar_link">
    <visual>
      <origin xyz="-0.0275 -0.0275 -0.02" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://${package_name}/meshes/Lidar_pacecat.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
  </link>
  <gazebo reference="lidar_link">
    <sensor name='gpu_lidar' type='gpu_lidar'>
      <ignition_frame_id>lidar_link</ignition_frame_id> 
      <update_rate>$(arg lidar_frequency)</update_rate> <!-- MHz -->
      <ray>
        <scan>
          <horizontal>
            <samples>$(arg horizontal_samples)</samples>
            <resolution>$(arg horizontal_resolution)</resolution>
            <min_angle>$(arg horizontal_min_angle)</min_angle>
            <max_angle>$(arg horizontal_max_angle)</max_angle>
          </horizontal>
          <vertical>
            <samples>$(arg vertical_samples)</samples>     
            <resolution>$(arg vertical_resolution)</resolution>
            <min_angle>$(arg vertical_min_angle)</min_angle> <!-- -45 deg -->
            <max_angle>$(arg vertical_max_angle)</max_angle> <!-- +45 deg -->
          </vertical>
        </scan>
        <range>
          <min>$(arg min_distance)</min>
          <max>$(arg max_distance)</max>
          <resolution>$(arg resolution)</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <alwaysOn>1</alwaysOn>
      <visualize>false</visualize>

      <topic>lidar</topic>
    </sensor>
  </gazebo>

    <!-- RGBD CAMERA -->
  <joint name="rgbd_camera_joint" type="fixed">
    <origin xyz="0.05 0 0.06" rpy="0 ${-PI/4} 0"/>
    <parent link="base_link"/>
    <child link="rgbd_camera_frame"/>
  </joint>
  <link name="rgbd_camera_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.07 0.03"/>
      </geometry>
      <material name="white">
        <color rgba="0.9 0.9 0.9 1.0"/>
      </material>
    </visual>
  </link>

  <gazebo reference="rgbd_camera_frame">
    <sensor name="rgbd_camera" type="rgbd_camera">
      <ignition_frame_id>rgbd_camera_frame</ignition_frame_id>
      <camera name="rgbd_camera_frame">
        <horizontal_fov>1.0472</horizontal_fov>
        <lens>
          <intrinsics>
            <!-- fx = fy = width / ( 2 * tan (hfov / 2 ) ) -->
            <fx>277.1</fx>
            <fy>277.1</fy>
            <!-- cx = ( width + 1 ) / 2 -->
            <cx>160.5</cx>
            <!-- cy = ( height + 1 ) / 2 -->
            <cy>120.5</cy>
            <s>0</s>
          </intrinsics>
        </lens>
        <distortion>
          <k1>0.0</k1>
          <k2>0.0</k2>
          <k3>0.0</k3>
          <p1>0.0</p1>
          <p2>0.0</p2>
          <center>0.5 0.5</center>
        </distortion>
        <image>
          <width>320</width>
          <height>240</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.01</near>
          <far>300</far>
        </clip>
        <depth_camera>
          <clip>
            <near>0.1</near>
            <far>10</far>
          </clip>
        </depth_camera>
        <noise>
          <type>gaussian</type>
          <mean>0</mean>
          <stddev>0.004</stddev>
        </noise>
      </camera>
      <always_on>1</always_on>
      <update_rate>10</update_rate>
      <visualize>0</visualize>
      <topic>depth_camera</topic>
    </sensor>
  </gazebo>

    <!-- IMU -->
  <gazebo reference="base_link">
    <sensor name="imu_sensor" type="imu">
      <ignition_frame_id>base_link</ignition_frame_id>
      <always_on>1</always_on>
      <update_rate>$(arg imu_frequency)</update_rate>
      <visualize>false</visualize>
      <topic>imu</topic>
      <imu>
        <enable_orientation>0</enable_orientation>
        <angular_velocity>
          <x>
            <noise type="gaussian">
              <mean>0</mean>
              <stddev>0.009</stddev>
              <bias_mean>0.00075</bias_mean>
              <bias_stddev>0.005</bias_stddev>
              <dynamic_bias_stddev>0.00002</dynamic_bias_stddev>
              <dynamic_bias_correlation_time>400.0</dynamic_bias_correlation_time>
              <precision>0.00025</precision>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0</mean>
              <stddev>0.009</stddev>
              <bias_mean>0.00075</bias_mean>
              <bias_stddev>0.005</bias_stddev>
              <dynamic_bias_stddev>0.00002</dynamic_bias_stddev>
              <dynamic_bias_correlation_time>400.0</dynamic_bias_correlation_time>
              <precision>0.00025</precision>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0</mean>
              <stddev>0.009</stddev>
              <bias_mean>0.00075</bias_mean>
              <bias_stddev>0.005</bias_stddev>
              <dynamic_bias_stddev>0.00002</dynamic_bias_stddev>
              <dynamic_bias_correlation_time>400.0</dynamic_bias_correlation_time>
              <precision>0.00025</precision>
            </noise>
          </z>
        </angular_velocity>
        <linear_acceleration>
          <x>
            <noise type="gaussian">
              <mean>0</mean>
              <stddev>0.021</stddev>
              <bias_mean>0.05</bias_mean>
              <bias_stddev>0.0075</bias_stddev>
              <dynamic_bias_stddev>0.000375</dynamic_bias_stddev>
              <dynamic_bias_correlation_time>175.0</dynamic_bias_correlation_time>
              <precision>0.005</precision>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0</mean>
              <stddev>0.021</stddev>
              <bias_mean>0.05</bias_mean>
              <bias_stddev>0.0075</bias_stddev>
              <dynamic_bias_stddev>0.000375</dynamic_bias_stddev>
              <dynamic_bias_correlation_time>175.0</dynamic_bias_correlation_time>
              <precision>0.005</precision>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0</mean>
              <stddev>0.021</stddev>
              <bias_mean>0.05</bias_mean>
              <bias_stddev>0.0075</bias_stddev>
              <dynamic_bias_stddev>0.000375</dynamic_bias_stddev>
              <dynamic_bias_correlation_time>175.0</dynamic_bias_correlation_time>
              <precision>0.005</precision>
            </noise>
          </z>
        </linear_acceleration>
      </imu>
    </sensor>
  </gazebo>

  <!-- ************************* PLUGIN DEFINITIONS ************************* -->
  <gazebo>

    <plugin
      filename="ignition-gazebo-ackermann-steering-system"
      name="gz::sim::systems::AckermannSteering">
      <left_joint>leftfront_joint</left_joint>
      <left_joint>leftback_joint</left_joint>
      <right_joint>rightfront_joint</right_joint>
      <right_joint>rightback_joint</right_joint>

      <left_steering_joint>front_left_wheel_steering_joint</left_steering_joint>
      <right_steering_joint>front_right_wheel_steering_joint</right_steering_joint>

      <kingpin_width>1.0</kingpin_width>
      <steering_limit>0.4</steering_limit>
      <wheel_base>1.0</wheel_base>
      <wheel_separation>${2*L_x}</wheel_separation>
      <wheel_radius>${wheelDiameter/2}</wheel_radius>
      <odom_publish_frequency>20</odom_publish_frequency>
      <min_velocity>-1</min_velocity>
      <max_velocity>1</max_velocity>
      <min_acceleration>-3</min_acceleration>
      <max_acceleration>3</max_acceleration>
      <odom_topic>encoder</odom_topic> <!-- THIS TAG IS REQUIRED TO USE THE WORLD PLUING -->
    </plugin>

    <!-- World odometry plugin -->
    <plugin filename="ignition-gazebo-odometry-publisher-system"
      name="ignition::gazebo::systems::OdometryPublisher">
      <dimensions>3</dimensions>
      <robot_base_frame>base_footprint</robot_base_frame>
      <publish_link_pose>true</publish_link_pose> 
    </plugin>


    <!-- <plugin
    filename="gz-sim-pose-publisher-system"
    name="gz::sim::systems::PosePublisher">
    <publish_link_pose>true</publish_link_pose>
    <use_pose_vector_msg>true</use_pose_vector_msg>
    <publish_nested_model_pose>true</publish_nested_model_pose>
    </plugin> -->
        
    <plugin
      filename="ignition-gazebo-joint-state-publisher-system"
      name="ignition::gazebo::systems::JointStatePublisher">
    </plugin>
      
  </gazebo>
  
</robot>